import { reactRouter } from "@react-router/dev/vite";
import tailwindcss from "@tailwindcss/vite";
import { defineConfig } from "vite";
import tsconfigPaths from "vite-tsconfig-paths";
import AutoImport from "unplugin-auto-import/vite";

export default defineConfig({
  plugins: [
    tailwindcss(),
    AutoImport({
      dts: "./auto-imports.d.ts",
      imports: [
        {
          react: [
            "useState",
            "useEffect",
            "useMemo",
            "useCallback",
            "useRef",
            "useContext",
            "useReducer",
            "useId",
            "useLayoutEffect",
            "createElement",
            "Fragment",
            "isValidElement",
            "cloneElement",
          ],
          "~/builder": [
            "UI",
            "ui",
            "createPage",
            "defineRoute",
            "createMeta",
            "cacheHeaders",
            "CACHE_PRESETS",
            "routes",
            "logger",
            "Div",
            "Row",
            "Col",
            "Span",
            "P",
            "H1",
            "H2",
            "H3",
            "Section",
            "Main",
            "Header",
            "Aside",
            "Nav",
            "Ul",
            "Li",
            "Card",
            "Badge",
            "Button",
            "SubmitButton",
            "Table",
            "Input",
            "Select",
            "Textarea",
            "Modal",
            "Form",
            "Breadcrumb",
            "Link",
            "Icon",
            "Suspense",
            "Await",
            "Skeleton",
            "ClientOnly",
            "Chart",
            "PrintButton",
            "OfflineBanner",
            "Custom",
            "renderElement",
            "useAuthPermission",
            "PermissionGuard",
            "PermissionProvider",
            "hasRole",
            "hasPermission",
            "getUserPermissions",
            "checkMetaAccess",
            "ROLES",
            "PERMISSIONS",
            "extractUrlState",
            "buildEncryptedUrl",
            "successResponse",
            "errorResponse",
            "ApiError",
            "unwrapApiResponse",
            "isApiSuccess",
            "isApiError",
            "ConfirmDialog",
            "modals",
            "UserAvatarColumn",
            "BadgeColumn",
            "TextColumn",
            "TableActions",
            "PageHeader",
            "StatsGrid",
            "RbacSimulatorBanner",
            "FilterBar",
            "UserGrowthChart",
          ],
          "~/lib/middleware.server": [
            "withMiddleware",
            "withTelemetry",
            "rateLimitMiddleware",
            "requireAuthMiddleware",
            "optionalAuthMiddleware",
            "metaAccessMiddleware",
          ],
          "~/lib/api": ["ErrorCatch"],
          "~/constants/brand": ["BRAND_NAME", "BRAND_TAGLINE", "BRAND_DESCRIPTION"],
        },
      ],
    }),
    reactRouter(),
    tsconfigPaths(),
  ],
  define: {
    'process.env': {},
  },
  resolve: {
    dedupe: [
      "react",
      "react-dom",
      "firebase/app",
      "@firebase/app",
      "firebase/auth",
      "@firebase/auth",
      "firebase/firestore",
      "@firebase/firestore",
    ],
  },
  optimizeDeps: {
    include: [
      "react-to-print",
      "firebase/app",
      "firebase/auth",
      "firebase/firestore",
    ],
  },
  ssr: {
    noExternal: [
      "@react-pdf/renderer",
      "@react-pdf/font",
      "@react-pdf/layout",
      "@react-pdf/pdfkit",
      "@react-pdf/primitives",
      "@react-pdf/stylesheet",
      "@react-pdf/yoga",
      "pdfkit",
    ],
  },
});
