import { z } from 'zod';

export const AgentStatusSchema = z.enum(['working', 'meeting', 'away', 'break', 'offline']);
export type AgentStatus = z.infer<typeof AgentStatusSchema>;

export const DivisionSchema = z.enum([
  'sales',
  'marketing',
  'operations',
  'communication',
  'development',
  'finance',
  'general_hr',
]);
export type Division = z.infer<typeof DivisionSchema>;

export const AGENT_STATUS_CONFIG: Record<
  AgentStatus,
  { label: string; color: string; ringColor: string; bgClass: string; textClass: string; hexColor: number }
> = {
  working: {
    label: 'Sedang Bekerja',
    color: '#10b981',
    ringColor: '#34d399',
    bgClass: 'bg-emerald-500/10 border-emerald-500/30 text-emerald-600',
    textClass: 'text-emerald-600',
    hexColor: 0x10b981,
  },
  meeting: {
    label: 'Dalam Rapat',
    color: '#8b5cf6',
    ringColor: '#a78bfa',
    bgClass: 'bg-purple-500/10 border-purple-500/30 text-purple-600',
    textClass: 'text-purple-600',
    hexColor: 0x8b5cf6,
  },
  away: {
    label: 'Tidak di Meja',
    color: '#64748b',
    ringColor: '#94a3b8',
    bgClass: 'bg-slate-500/10 border-slate-500/30 text-slate-600',
    textClass: 'text-slate-600',
    hexColor: 0x64748b,
  },
  break: {
    label: 'Istirahat / Kopi',
    color: '#f59e0b',
    ringColor: '#fbbf24',
    bgClass: 'bg-amber-500/10 border-amber-500/30 text-amber-600',
    textClass: 'text-amber-600',
    hexColor: 0xf59e0b,
  },
  offline: {
    label: 'Offline',
    color: '#ef4444',
    ringColor: '#f87171',
    bgClass: 'bg-red-500/10 border-red-500/30 text-red-600',
    textClass: 'text-red-600',
    hexColor: 0xef4444,
  },
};

export const DIVISION_CONFIG: Record<
  Division,
  { name: string; shortName: string; icon: string; color: string; shirtHex: number; cameraTarget: [number, number, number] }
> = {
  sales: {
    name: 'Sales & Business Development',
    shortName: 'SALES',
    icon: 'Briefcase',
    color: '#0284c7',
    shirtHex: 0x0369a1,
    cameraTarget: [-9.5, 0.8, -8.0],
  },
  marketing: {
    name: 'Brand & Growth Marketing',
    shortName: 'MARKETING',
    icon: 'TrendingUp',
    color: '#db2777',
    shirtHex: 0xbe185d,
    cameraTarget: [-9.5, 0.8, -0.5],
  },
  operations: {
    name: 'Operations & Supply Chain',
    shortName: 'OPERATIONS',
    icon: 'Layers',
    color: '#d97706',
    shirtHex: 0xb45309,
    cameraTarget: [-9.5, 0.8, 7.5],
  },
  communication: {
    name: 'Corporate Communication & PR',
    shortName: 'COMMUNICATION',
    icon: 'Radio',
    color: '#059669',
    shirtHex: 0x047857,
    cameraTarget: [4.5, 0.8, -8.5],
  },
  development: {
    name: 'Software Engineering & IT',
    shortName: 'DEVELOPMENT',
    icon: 'Code',
    color: '#2563eb',
    shirtHex: 0x1d4ed8,
    cameraTarget: [6.5, 0.8, -1.0],
  },
  finance: {
    name: 'Finance & Accounting',
    shortName: 'FINANCE',
    icon: 'DollarSign',
    color: '#7c3aed',
    shirtHex: 0x6d28d9,
    cameraTarget: [4.5, 0.8, 6.5],
  },
  general_hr: {
    name: 'General Affairs & People HR',
    shortName: 'GENERAL / HR',
    icon: 'Users',
    color: '#ea580c',
    shirtHex: 0xc2410c,
    cameraTarget: [12.0, 0.8, -4.5],
  },
};

export const AgentSchema = z.object({
  id: z.string(),
  name: z.string().min(2),
  role: z.string(),
  division: DivisionSchema,
  status: AgentStatusSchema,
  avatarColor: z.string().default('#38bdf8'),
  shirtColor: z.string().default('#0284c7'),
  currentTask: z.string().default('Menangani tugas operasional'),
  currentProject: z.string().default('Kinau Enterprise Platform'),
  deskId: z.string(),
  position: z.tuple([z.number(), z.number(), z.number()]), // [x, y, z]
  rotationY: z.number().default(0), // in radians
  focusScore: z.number().min(0).max(100).default(92),
  focusTime: z.string().default('3j 45m'),
  lastActive: z.string().default('Aktif sekarang'),
  initialMessage: z.string().optional(),
});

export type Agent = z.infer<typeof AgentSchema>;

export const OfficeZoneSchema = z.object({
  id: z.string(),
  name: z.string(),
  code: DivisionSchema,
  capacity: z.number(),
  color: z.string(),
  description: z.string(),
  centerPos: z.tuple([z.number(), z.number(), z.number()]),
});

export type OfficeZone = z.infer<typeof OfficeZoneSchema>;

export const UpdateAgentStatusSchema = z.object({
  agentId: z.string(),
  status: AgentStatusSchema,
});

export const AssignTaskSchema = z.object({
  agentId: z.string(),
  task: z.string().min(3, 'Tugas minimal 3 karakter'),
  project: z.string().optional(),
});

export const SendMessageSchema = z.object({
  agentId: z.string(),
  message: z.string().min(1, 'Pesan tidak boleh kosong'),
});

// Zones configuration matching reference layout
export const INITIAL_OFFICE_ZONES: OfficeZone[] = [
  { id: 'zone-sales', name: 'Sales & Business Development', code: 'sales', capacity: 6, color: '#0284c7', description: 'Divisi Penjualan & Kemitraan Klien', centerPos: [-9.5, 0, -8.0] },
  { id: 'zone-mkt', name: 'Brand & Growth Marketing', code: 'marketing', capacity: 6, color: '#db2777', description: 'Divisi Pemasaran, Iklan & Kreatif', centerPos: [-9.5, 0, -0.5] },
  { id: 'zone-ops', name: 'Operations & Supply Chain', code: 'operations', capacity: 6, color: '#d97706', description: 'Divisi Logistik, Gudang & Produksi', centerPos: [-9.5, 0, 7.5] },
  { id: 'zone-comm', name: 'Corporate Communication & PR', code: 'communication', capacity: 6, color: '#059669', description: 'Divisi Humas & Media Komunikasi', centerPos: [4.5, 0, -8.5] },
  { id: 'zone-dev', name: 'Software Engineering & IT', code: 'development', capacity: 8, color: '#2563eb', description: 'Divisi Rekayasa Perangkat Lunak & Cloud', centerPos: [4.5, 0, -1.0] },
  { id: 'zone-fin', name: 'Finance & Accounting', code: 'finance', capacity: 6, color: '#7c3aed', description: 'Divisi Keuangan, Pajak & Pembukuan', centerPos: [4.5, 0, 6.5] },
  { id: 'zone-hr', name: 'General Affairs & People HR', code: 'general_hr', capacity: 4, color: '#ea580c', description: 'Divisi SDM, Rekrutmen & Fasilitas', centerPos: [12.0, 0, -4.5] },
];

// 26 Workstations & Seated Agents mapped identically to the visual blocks
export const INITIAL_AGENTS: Agent[] = [
  // --- SALES (Top Left) ---
  {
    id: 'agent-sales-1',
    name: 'Rian Hidayat',
    role: 'Senior Enterprise Account Executive',
    division: 'sales',
    status: 'working',
    avatarColor: '#0284c7',
    shirtColor: '#0369a1',
    currentTask: 'Closing proposal vendor apparel Q4',
    currentProject: 'B2B Enterprise Partnership',
    deskId: 'desk-sales-1',
    position: [-11.5, 0, -9.5],
    rotationY: 0,
    focusScore: 96,
    focusTime: '4j 10m',
    lastActive: 'Aktif sekarang',
  },
  {
    id: 'agent-sales-2',
    name: 'Jessica Tan',
    role: 'Sales Development Representative',
    division: 'sales',
    status: 'working',
    avatarColor: '#0ea5e9',
    shirtColor: '#0284c7',
    currentTask: 'Cold outreach & follow-up lead inbound',
    currentProject: 'Inbound Growth Campaign',
    deskId: 'desk-sales-2',
    position: [-7.5, 0, -9.5],
    rotationY: 0,
    focusScore: 92,
    focusTime: '3j 30m',
    lastActive: 'Aktif sekarang',
  },
  {
    id: 'agent-sales-3',
    name: 'Bagus Pratama',
    role: 'Client Relationship Manager',
    division: 'sales',
    status: 'meeting',
    avatarColor: '#38bdf8',
    shirtColor: '#0369a1',
    currentTask: 'Meeting negosiasi kontrak korporat',
    currentProject: 'Corporate Retainer 2026',
    deskId: 'desk-sales-3',
    position: [-11.5, 0, -6.5],
    rotationY: Math.PI,
    focusScore: 88,
    focusTime: '2j 15m',
    lastActive: 'Dalam meeting',
  },
  {
    id: 'agent-sales-4',
    name: 'Cindy Larasati',
    role: 'B2B Sales Specialist',
    division: 'sales',
    status: 'working',
    avatarColor: '#0284c7',
    shirtColor: '#0284c7',
    currentTask: 'Penyusunan pricelist kustom jersey',
    currentProject: 'Sport Club Customizer',
    deskId: 'desk-sales-4',
    position: [-7.5, 0, -6.5],
    rotationY: Math.PI,
    focusScore: 94,
    focusTime: '3j 45m',
    lastActive: 'Aktif sekarang',
  },

  // --- MARKETING (Middle Left) ---
  {
    id: 'agent-mkt-1',
    name: 'Sarah Amanda',
    role: 'Head of Brand & Growth Marketing',
    division: 'marketing',
    status: 'working',
    avatarColor: '#db2777',
    shirtColor: '#be185d',
    currentTask: 'Optimasi Meta & Google Ads conversion rate',
    currentProject: 'Customizer 3D Launch Blitz',
    deskId: 'desk-mkt-1',
    position: [-11.5, 0, -2.0],
    rotationY: 0,
    focusScore: 95,
    focusTime: '5j 00m',
    lastActive: 'Aktif sekarang',
  },
  {
    id: 'agent-mkt-2',
    name: 'Rico Firmansyah',
    role: 'Creative Motion & 3D Designer',
    division: 'marketing',
    status: 'working',
    avatarColor: '#ec4899',
    shirtColor: '#db2777',
    currentTask: 'Render asset video promosi mockup 3D',
    currentProject: 'Kinau Brand Assets',
    deskId: 'desk-mkt-2',
    position: [-7.5, 0, -2.0],
    rotationY: 0,
    focusScore: 97,
    focusTime: '4j 20m',
    lastActive: 'Aktif sekarang',
  },
  {
    id: 'agent-mkt-3',
    name: 'Dinda Maharani',
    role: 'Content & Social Media Strategist',
    division: 'marketing',
    status: 'break',
    avatarColor: '#f472b6',
    shirtColor: '#be185d',
    currentTask: 'Jadwal posting TikTok & Reels showcase',
    currentProject: 'Viral Engagement Strategy',
    deskId: 'desk-mkt-3',
    position: [-11.5, 0, 1.0],
    rotationY: Math.PI,
    focusScore: 84,
    focusTime: '1j 40m',
    lastActive: 'Istirahat kopi',
  },
  {
    id: 'agent-mkt-4',
    name: 'Kevin Julian',
    role: 'Performance Marketing Specialist',
    division: 'marketing',
    status: 'working',
    avatarColor: '#db2777',
    shirtColor: '#be185d',
    currentTask: 'Analisis ROAS & CAC dashboard',
    currentProject: 'Analytics Revenue Attribution',
    deskId: 'desk-mkt-4',
    position: [-7.5, 0, 1.0],
    rotationY: Math.PI,
    focusScore: 91,
    focusTime: '3j 10m',
    lastActive: 'Aktif sekarang',
  },

  // --- OPERATIONS (Bottom Left) ---
  {
    id: 'agent-ops-1',
    name: 'Agus Setiawan',
    role: 'Operations & Production Manager',
    division: 'operations',
    status: 'working',
    avatarColor: '#d97706',
    shirtColor: '#b45309',
    currentTask: 'Monitoring antrian cetak sublimasi & jahit',
    currentProject: 'Workshop Production Stream',
    deskId: 'desk-ops-1',
    position: [-11.5, 0, 6.0],
    rotationY: 0,
    focusScore: 93,
    focusTime: '4j 15m',
    lastActive: 'Aktif sekarang',
  },
  {
    id: 'agent-ops-2',
    name: 'Wahyu Ramadhan',
    role: 'Inventory & Supply Chain Specialist',
    division: 'operations',
    status: 'working',
    avatarColor: '#f59e0b',
    shirtColor: '#d97706',
    currentTask: 'Audit stok kain Dryfit & tinta sublimasi',
    currentProject: 'Warehouse Inventory ERP',
    deskId: 'desk-ops-2',
    position: [-7.5, 0, 6.0],
    rotationY: 0,
    focusScore: 89,
    focusTime: '3j 05m',
    lastActive: 'Aktif sekarang',
  },
  {
    id: 'agent-ops-3',
    name: 'Ratna Dewi',
    role: 'Quality Assurance & Packaging Lead',
    division: 'operations',
    status: 'away',
    avatarColor: '#fbbf24',
    shirtColor: '#b45309',
    currentTask: 'Inspeksi hasil cetak batch #1042',
    currentProject: 'Quality Control Standard',
    deskId: 'desk-ops-3',
    position: [-11.5, 0, 9.0],
    rotationY: Math.PI,
    focusScore: 82,
    focusTime: '2j 00m',
    lastActive: 'Di area produksi',
  },
  {
    id: 'agent-ops-4',
    name: 'Eko Prasetyo',
    role: 'Fulfillment & Logistics Officer',
    division: 'operations',
    status: 'working',
    avatarColor: '#d97706',
    shirtColor: '#b45309',
    currentTask: 'Dispatching paket kurir ekspedisi',
    currentProject: 'Same-Day Dispatch Service',
    deskId: 'desk-ops-4',
    position: [-7.5, 0, 9.0],
    rotationY: Math.PI,
    focusScore: 90,
    focusTime: '3j 20m',
    lastActive: 'Aktif sekarang',
  },

  // --- COMMUNICATION (Top Right) ---
  {
    id: 'agent-comm-1',
    name: 'Nabila Azzahra',
    role: 'Public Relations & Communication Lead',
    division: 'communication',
    status: 'working',
    avatarColor: '#059669',
    shirtColor: '#047857',
    currentTask: 'Penyusunan press release kolaborasi brand',
    currentProject: 'PR Brand Exposure 2026',
    deskId: 'desk-comm-1',
    position: [2.5, 0, -10.0],
    rotationY: 0,
    focusScore: 94,
    focusTime: '3j 50m',
    lastActive: 'Aktif sekarang',
  },
  {
    id: 'agent-comm-2',
    name: 'Farhan Maulana',
    role: 'Customer Support Lead',
    division: 'communication',
    status: 'working',
    avatarColor: '#10b981',
    shirtColor: '#059669',
    currentTask: 'Menangani tiket live chat & revisi desain',
    currentProject: 'Omnichannel CS Hub',
    deskId: 'desk-comm-2',
    position: [6.5, 0, -10.0],
    rotationY: 0,
    focusScore: 91,
    focusTime: '4j 30m',
    lastActive: 'Aktif sekarang',
  },
  {
    id: 'agent-comm-3',
    name: 'Gita Savitri',
    role: 'Media Relations Specialist',
    division: 'communication',
    status: 'meeting',
    avatarColor: '#34d399',
    shirtColor: '#047857',
    currentTask: 'Briefing media partner & podcast sponsor',
    currentProject: 'Podcast Sponsorship Deal',
    deskId: 'desk-comm-3',
    position: [2.5, 0, -7.0],
    rotationY: Math.PI,
    focusScore: 87,
    focusTime: '1j 50m',
    lastActive: 'Meeting media',
  },
  {
    id: 'agent-comm-4',
    name: 'Iqbal Kurnia',
    role: 'Community Manager',
    division: 'communication',
    status: 'working',
    avatarColor: '#059669',
    shirtColor: '#047857',
    currentTask: 'Moderasi Discord komunitas desainer jersey',
    currentProject: 'Kinau Creator Guild',
    deskId: 'desk-comm-4',
    position: [6.5, 0, -7.0],
    rotationY: Math.PI,
    focusScore: 92,
    focusTime: '3j 15m',
    lastActive: 'Aktif sekarang',
  },

  // --- DEVELOPMENT / DELIVERY (Middle Right) ---
  {
    id: 'agent-dev-dito',
    name: 'Dito',
    role: 'QA Analyst',
    division: 'development',
    status: 'working',
    avatarColor: '#2563eb',
    shirtColor: '#1d4ed8',
    currentTask: 'Automated E2E Testing & UI regression audit',
    currentProject: 'Quality Assurance Matrix',
    deskId: 'desk-dev-dito',
    position: [2.5, 0, -2.5],
    rotationY: 0,
    focusScore: 93,
    focusTime: '3j 50m',
    lastActive: 'Aktif sekarang',
    initialMessage:
      'Semua test suite dan audit regresi UI sudah hijau. Siap dideploy ke staging environment.',
  },
  {
    id: 'agent-dev-putri',
    name: 'Putri',
    role: 'Project Coordinator',
    division: 'development',
    status: 'working',
    avatarColor: '#60a5fa',
    shirtColor: '#1d4ed8',
    currentTask: 'Sprint planning & koordinasi milestone release',
    currentProject: 'Kinau Sprint Delivery',
    deskId: 'desk-dev-putri',
    position: [6.5, 0, -2.5],
    rotationY: 0,
    focusScore: 94,
    focusTime: '4j 10m',
    lastActive: 'Aktif sekarang',
    initialMessage:
      'Sprint minggu ini berjalan on-track, semua blocker teknis sudah kita eskalasi ke lead engineer.',
  },
  {
    id: 'agent-dev-damar',
    name: 'Damar',
    role: 'Delivery Lead',
    division: 'development',
    status: 'working',
    avatarColor: '#3b82f6',
    shirtColor: '#1d4ed8',
    currentTask: 'Review roadmap & arsitektur pipeline delivery',
    currentProject: 'Core Delivery Engine',
    deskId: 'desk-dev-damar',
    position: [10.5, 0, -2.5],
    rotationY: 0,
    focusScore: 97,
    focusTime: '5j 10m',
    lastActive: 'Aktif sekarang',
    initialMessage:
      'Roadmap Q4 sudah final. Arsitektur pipeline delivery kita optimasi untuk zero-latency sync.',
  },
  {
    id: 'agent-dev-dara',
    name: 'Dara',
    role: 'Design Assistant',
    division: 'development',
    status: 'working',
    avatarColor: '#10b981',
    shirtColor: '#1d4ed8',
    currentTask: 'Checklist langkah, kartu first workflow & empty state knowledge base',
    currentProject: 'First Workflow UI System',
    deskId: 'desk-dev-dara',
    position: [2.5, 0, 0.5],
    rotationY: Math.PI,
    focusScore: 98,
    focusTime: '4j 30m',
    lastActive: 'Aktif sekarang',
    initialMessage:
      'Aku siapkan tiga arah: checklist langkah, kartu first workflow, dan empty state knowledge base. Pakai orange sebagai aksen aksi, teks ringkas, serta status yang tidak hanya mengandalkan warna. Semua konsep perlu dicocokkan dengan fitur yang sudah tersedia.',
  },
  {
    id: 'agent-dev-cassie',
    name: 'Cassie',
    role: 'Asset Coordinator',
    division: 'development',
    status: 'working',
    avatarColor: '#38bdf8',
    shirtColor: '#2563eb',
    currentTask: 'Sinkronisasi aset brand & panduan visual 3D UI',
    currentProject: 'Brand Design Architecture',
    deskId: 'desk-dev-cassie',
    position: [6.5, 0, 0.5],
    rotationY: Math.PI,
    focusScore: 95,
    focusTime: '4j 40m',
    lastActive: 'Aktif sekarang',
    initialMessage:
      'Halo! Panduan visual dan aset brand untuk workflow sudah siap disinkronkan ke tim frontend.',
  },
  {
    id: 'agent-dev-citra',
    name: 'Citra',
    role: 'Client Reporting',
    division: 'development',
    status: 'working',
    avatarColor: '#a855f7',
    shirtColor: '#1d4ed8',
    currentTask: 'Penyusunan laporan performa delivery mingguan',
    currentProject: 'Client Reporting Dashboard',
    deskId: 'desk-dev-citra',
    position: [10.5, 0, 0.5],
    rotationY: Math.PI,
    focusScore: 91,
    focusTime: '3j 20m',
    lastActive: 'Aktif sekarang',
    initialMessage:
      'Laporan progres klien sudah saya compile ke PDF dan siap dikirim via portal terpadu.',
  },
  {
    id: 'agent-dev-ona',
    name: 'Ona',
    role: 'Onboarding Specialist',
    division: 'development',
    status: 'working',
    avatarColor: '#f97316',
    shirtColor: '#1d4ed8',
    currentTask: 'Panduan onboarding agen baru & knowledge base',
    currentProject: 'Team Onboarding Portal',
    deskId: 'desk-dev-ona',
    position: [6.5, 0, 3.5],
    rotationY: 0,
    focusScore: 92,
    focusTime: '3j 30m',
    lastActive: 'Aktif sekarang',
    initialMessage:
      'Semua modul onboarding agent baru sudah lengkap dengan video interaktif dan checklist tugas.',
  },

  // --- FINANCE (Bottom Right) ---
  {
    id: 'agent-fin-1',
    name: 'Maya Kusuma',
    role: 'Finance & Accounting Lead',
    division: 'finance',
    status: 'working',
    avatarColor: '#7c3aed',
    shirtColor: '#6d28d9',
    currentTask: 'Rekonsiliasi transaksi gateway & invoice B2B',
    currentProject: 'NuraFin Automated Cashflow',
    deskId: 'desk-fin-1',
    position: [2.5, 0, 5.0],
    rotationY: 0,
    focusScore: 96,
    focusTime: '4j 50m',
    lastActive: 'Aktif sekarang',
  },
  {
    id: 'agent-fin-2',
    name: 'Teguh Wibowo',
    role: 'Tax & Compliance Specialist',
    division: 'finance',
    status: 'working',
    avatarColor: '#8b5cf6',
    shirtColor: '#7c3aed',
    currentTask: 'Laporan SPT Masa PPh & PPN e-Faktur',
    currentProject: 'Corporate Tax Compliance',
    deskId: 'desk-fin-2',
    position: [6.5, 0, 5.0],
    rotationY: 0,
    focusScore: 91,
    focusTime: '3j 25m',
    lastActive: 'Aktif sekarang',
  },
  {
    id: 'agent-fin-3',
    name: 'Lestari Handayani',
    role: 'Payroll & Treasury Officer',
    division: 'finance',
    status: 'working',
    avatarColor: '#a78bfa',
    shirtColor: '#6d28d9',
    currentTask: 'Disbursement gaji & bonus tim bulan ini',
    currentProject: 'Automated Payroll Pipeline',
    deskId: 'desk-fin-3',
    position: [2.5, 0, 8.0],
    rotationY: Math.PI,
    focusScore: 94,
    focusTime: '4j 00m',
    lastActive: 'Aktif sekarang',
  },
  {
    id: 'agent-fin-4',
    name: 'Hendra Gunawan',
    role: 'Cost Accounting Analyst',
    division: 'finance',
    status: 'break',
    avatarColor: '#7c3aed',
    shirtColor: '#6d28d9',
    currentTask: 'Analisis HPP (Harga Pokok Produksi) per kain',
    currentProject: 'Margin Optimization Analysis',
    deskId: 'desk-fin-4',
    position: [6.5, 0, 8.0],
    rotationY: Math.PI,
    focusScore: 85,
    focusTime: '2j 10m',
    lastActive: 'Sedang break',
  },

  // --- GENERAL / HR (Far Right) ---
  {
    id: 'agent-hr-1',
    name: 'Nadia Kirana',
    role: 'Head of People & HR Operations',
    division: 'general_hr',
    status: 'working',
    avatarColor: '#ea580c',
    shirtColor: '#c2410c',
    currentTask: 'Interview calon Senior 3D Designer',
    currentProject: 'Q4 Talent Acquisition',
    deskId: 'desk-hr-1',
    position: [12.0, 0, -6.0],
    rotationY: 0,
    focusScore: 95,
    focusTime: '3j 40m',
    lastActive: 'Aktif sekarang',
  },
  {
    id: 'agent-hr-2',
    name: 'Rudi Hartono',
    role: 'General Affairs & Facility Officer',
    division: 'general_hr',
    status: 'working',
    avatarColor: '#f97316',
    shirtColor: '#ea580c',
    currentTask: 'Pemeliharaan fasilitas AC & server room',
    currentProject: 'Office Facility Maintenance',
    deskId: 'desk-hr-2',
    position: [12.0, 0, -3.0],
    rotationY: Math.PI,
    focusScore: 89,
    focusTime: '2j 45m',
    lastActive: 'Aktif sekarang',
  },
];
